import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for Isaac Navigation Systems
  isaacNavigationSidebar: [
    {
      type: 'category',
      label: 'Isaac Navigation Systems',
      items: [
        'isaac-navigation-systems/index',
        {
          type: 'category',
          label: 'Isaac Sim',
          items: [
            'isaac-navigation-systems/isaac-sim/index',
          ],
        },
        {
          type: 'category',
          label: 'Isaac ROS',
          items: [
            'isaac-navigation-systems/isaac-ros/index',
          ],
        },
        {
          type: 'category',
          label: 'Nav2',
          items: [
            'isaac-navigation-systems/nav2/index',
          ],
        },
      ],
    },
  ],

  // Manual sidebar for Module 4: VLA, Planning & Capstone
  module4Sidebar: [
    {
      type: 'category',
      label: 'Module 4: VLA, Planning & Capstone',
      items: [
        'module-4-vla-planning-capstone/index',
        {
          type: 'category',
          label: 'Chapter 1: VLA Models',
          items: [
            'module-4-vla-planning-capstone/vla-models/index',
            'module-4-vla-planning-capstone/vla-models/foundation-models',
            'module-4-vla-planning-capstone/vla-models/multimodal-integration',
            'module-4-vla-planning-capstone/vla-models/vla-architectures',
            'module-4-vla-planning-capstone/vla-models/implementation',
            'module-4-vla-planning-capstone/vla-models/practice-examples',
            'module-4-vla-planning-capstone/vla-models/challenges',
            'module-4-vla-planning-capstone/vla-models/assessment',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Planning & Control',
          items: [
            'module-4-vla-planning-capstone/planning-control/index',
            'module-4-vla-planning-capstone/planning-control/path-planning-algorithms',
            'module-4-vla-planning-capstone/planning-control/trajectory-optimization',
            'module-4-vla-planning-capstone/planning-control/task-planning',
            'module-4-vla-planning-capstone/planning-control/reactive-planning',
            'module-4-vla-planning-capstone/planning-control/manipulation-planning',
            'module-4-vla-planning-capstone/planning-control/whole-body-planning',
            'module-4-vla-planning-capstone/planning-control/practice-examples',
            'module-4-vla-planning-capstone/planning-control/assessment',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Capstone Project',
          items: [
            'module-4-vla-planning-capstone/capstone/index',
            'module-4-vla-planning-capstone/capstone/project-requirements',
            'module-4-vla-planning-capstone/capstone/integration-guide',
            'module-4-vla-planning-capstone/capstone/implementation-phases',
            'module-4-vla-planning-capstone/capstone/testing-validation',
            'module-4-vla-planning-capstone/capstone/presentation-guidelines',
            'module-4-vla-planning-capstone/capstone/example-projects',
            'module-4-vla-planning-capstone/capstone/grading-rubric',
          ],
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
